### ISSUE TITLE
Windows11 arm64 support

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#37]
https://uupdump.net/

**Comment by ddkwork** [comment]
My knowledge of vt-x is still in the use stage, so I don't know if the cpu of mobile architecture has vt-x features. However, mobile devices are very portable, and most of the current development work is done on Android phones. At present, we are going to install Windows11 arm64 version on Android phones. If hyperdbg supports compiling arm64 version, it will be even better. The pain point of writing Windows-related code on a non-pc is that you can't access things like Windows sdk wdk, but once Win11 arm is installed on a mobile device, these situations will improve. Of course, this is only the understanding stage at present, and I hope it will go further in the future.

**Comment by ddkwork** [comment]
sudo apt install -y aria2

**Comment by SinaKarvandi** [comment]
Hi,
ARM processors have support for their own version of the hypervisor. It's not VT-x. The VT-x is only supported in Intel processors.

It's not simply possible to support ARM processors in HyperDbg, because there are completely different instructions, different concepts, and configurations. The thing is, HyperDbg has event-style managing and debugger support codes that can be used in all the microarchitectures (x86, x86_64, AARCH64 (ARM64), and even RISC-V) but first, we need to extract the hypervisor (vt-x) part of the HyperDbg from its source code (which is not a trivial task because we didn't assume this at the start of the project and now the project is too big to be changed). After that, we can start porting HyperDbg to other microarchitectures and other platforms (OSes) like Linux. The good news is, I started refactoring and separating the vt-x codes from the code base, however, it takes longer to be finished because the project is really big now.

**Comment by ddkwork** [comment]
> Hi,
> ARM processors have support for their own version of the hypervisor. It's not VT-x. The VT-x is only supported in Intel processors.
> 
> It's not simply possible to support ARM processors in HyperDbg, because there are completely different instructions, different concepts, and configurations. The thing is, HyperDbg has event-style managing and debugger support codes that can be used in all the microarchitectures (x86, x86_64, AARCH64 (ARM64), and even RISC-V) but first, we need to extract the hypervisor (vt-x) part of the HyperDbg from its source code (which is not a trivial task because we didn't assume this at the start of the project and now the project is too big to be changed). After that, we can start porting HyperDbg to other microarchitectures and other platforms (OSes) like Linux. The good news is, I started refactoring and separating the vt-x codes from the code base, however, it takes longer to be finished because the project is really big now.

good👍🏻
