### ISSUE TITLE
need fix LIST_ENTRY  struct

### ISSUE THREAD

**Issue by ddkwork** [HyperDbg/gui#39]
RequestStructures.h.go

//BreakpointsList LIST_ENTRY //todo can use list.list ?

**Comment by ddkwork** [comment]
> Hi,
> Is List.List the same structure as FLINK and BLINK in C. If not, I think it will break the semantics! (I mean the structure offset and how the kernel behaves to this structure).

At first, I thought that list and go std lib's list could have the same function. Then I thought that go std lib is a double linked list. Instead of guessing blindly, I might as well directly copy the list structure into go structure.

**Comment by ddkwork** [comment]
typedef struct _LIST_ENTRY {
  struct _LIST_ENTRY *Flink;
  struct _LIST_ENTRY *Blink;
} LIST_ENTRY, *PLIST_ENTRY, PRLIST_ENTRY;

Blink and Flink can be used pvoid type ？What's his fields？

**Comment by SinaKarvandi** [comment]
Yep, PVOID can be used instead of them. Blink and Flink are classic computer linked list data structures (https://bsodtutorials.wordpress.com/2013/10/27/linked-lists-flink-and-blink/).

Also, for your information, my friends and I are currently working on redesigning the script engine by using Antlr (https://www.antlr.org/). It takes a little bit of time, but after months, we'll have a refactored and separated code + SDK, and an extendable script engine to which users can contribute (because it's easy to extend), plus a lot of plugins for the VSCode, and also a good GUI thanks to you. Currently, I'm refactoring codes (https://github.com/HyperDbg/HyperDbg/tree/refactor-vcpu).

**Comment by ddkwork** [comment]
> Yep, PVOID can be used instead of them. Blink and Flink are classic computer linked list data structures (https://bsodtutorials.wordpress.com/2013/10/27/linked-lists-flink-and-blink/).
> 
> 是的，PVOID可以代替它们使用。Blink和Flink是典型的计算机链接列表数据结构（https://bsodtutorials.wordpress.com/2013/10/27/linked-lists-flink-and-blink/）.
> 
> Also, for your information, my friends and I are currently working on redesigning the script engine by using Antlr (https://www.antlr.org/). It takes a little bit of time, but after months, we'll have a refactored and separated code + SDK, and an extendable script engine to which users can contribute (because it's easy to extend), plus a lot of plugins for the VSCode, and also a good GUI thanks to you. Currently, I'm refactoring codes (https://github.com/HyperDbg/HyperDbg/tree/refactor-vcpu).
> 
> 另外，我和我的朋友目前正在使用Antlr（https://www.antlr.org/）.这需要一点时间，但几个月后，我们将有一个重构和分离的代码+ SDK，和一个可扩展的脚本引擎，用户可以贡献（因为它很容易扩展），加上许多插件的VSCode，也有一个很好的GUI感谢您。目前，我正在重构代码（https://github.com/HyperDbg/HyperDbg/tree/refactor-vcpu）.


![image](https://user-images.githubusercontent.com/19886504/205620646-e52b2990-39e3-49b6-9143-1223fc9e5847.png)

**Comment by ddkwork** [comment]
With regard to list entry, the std library of go language has a double-link container, which is instantiated as list.New (). However, in view of the data structure and memory alignment problems of the two languages, I think it is imperative to bind the c list structure. You can take time to write a unit test to test it.

**Comment by ddkwork** [comment]
I think of many aspects about the script engine. For example, design a set of syntax highlighting and script syntax keyword prompt for gui controls. In addition, once the data structure and memory alignment of the two languages are completely controllable, after passing various unit tests, I'm going to add the function of directly running go code to execute the same script as the script in addition to the script, so that I can open goland ide to quickly write the same function as the script, or call the script generation module of plugin directory. Unfortunately, I haven't seen such a control provided by skia lib at present, but as long as the properties of the rich text edit box control are available. At that time, it may be necessary for sdk to export more interfaces, such as those functions that ollydbg has: decoding the pe file section, then returning the relevant information of the reading process pe file section from dll. After this information is returned from dll to gui, we can use it to assist in removing the shell of themida, vmProtect, etc., and the subsequent VM code expansion also needs this information. For example, themida's cisc vm virtual machine, so with more interface exports of dll, it is convenient for us to write and execute the shelling script in gui, and even restore the inflated code of vm virtual machine.

**Comment by ddkwork** [comment]
vt-X's ept function is really powerful. Before using hyperdbg, I tested the ept hook cpu of various libraries, the serial number of hard disk, the capacity of hard disk and other structure-related api hooks, the mac address of network card, etc., which are not very stable or runs very slow. Then, I tested the hook random number for tls handshake binding of mitmproxy. Refactor vmx. You can test a wave of these functions I mentioned when you are free, especially linking ntdeviceiocontrol. Many libraries are runs very slow.

**Comment by SinaKarvandi** [comment]
Hi again,
Thanks for describing it to me.
Yes.

> For example, design a set of syntax highlighting
Yeah, exactly, because we're currently using antlr. It has its own highlighter. This means that we can easily, just by running a simple script, create a syntax highlighting plugin for all the platforms! We'll definitely do it.

>  I tested the hook random number for tls handshake binding of mitmproxy.

Another cool thing is, in the future (again, because we use antlr), we can easily add type, structure, and functions to the script engine, and it's pretty extendable. and another feature that might be interesting is converting the current script engine's IR format to the assembly code, which makes the script engine even faster. (the last one needs a little bit of investigation and
